version: 2

jobs:
  build:
    docker:
      - image: erdiko/docker-compose:1.11
    working_directory: /code

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - run: mkdir -p $TEST_RESULTS

      - run:
          name: Prep code (parent and sibling repos)
          command: |
            set -x

            chmod 770 scripts/ci/*.sh
            ./scripts/ci/install-user-admin.sh

            cd /code/user-admin

            pwd
            ls -al

      - setup_remote_docker

      - run:
          name: Build container environment
          command: |
            set -x

            pwd
            ls -al

            ./scripts/ci/build-ci.sh

      - run:
          name: Run PHPUnit tests
          command: |
            set -x

            docker exec -it erdiko_users_php /code/vendor/erdiko/users/scripts/ci-tests.sh

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
